package adventOfCode

//Assumes each string is the same length
fun stringDiff(str1: String, str2: String): Int {
    val out = str1.withIndex().map {
        it.value == str2[it.index]
    }
    return out.filter { !it }.count()
}

fun stringDiffIndex(str1: String, str2: String): Int {
    str1.withIndex().forEach {
        if (it.value != str2[it.index]) {
            return it.index
        }
    }
    return -1
}

fun findMissing(): String {
    val pairs = mutableListOf<Pair<String, String>>()
    val data = createDataDay2()
    data.withIndex().forEach { d ->
        data.subList(d.index + 1, data.size).forEach {
            if (stringDiff(d.value, it) == 1) {
                pairs.add(Pair(d.value, it))
            }
        }
    }
    val idx = stringDiffIndex(pairs.first().first, pairs.first().second)
    var out = ""
    for ((i, s) in pairs.first().first.withIndex()) {
        out += if (i != idx) {
            s
        } else {
            ""
        }
    }

    return out
}

fun createDataDay2(): List<String> = listOf(
    "bqlpzruexkszyahnamgjdctvfs",
    "bqlporuexkwyyahnbmgjdctvfb",
    "bqlhoruexkwzyahefmgjdctvfs",
    "bqlporuegkwzyahdimgodctvfs",
    "bqlporuxxkwhybhnimgjdctvfs",
    "dqlporuexkwzyahnimgjfcivfs",
    "bqlporlexkwzyarniigjdctvfs",
    "bqlporuezkqzeahnimgjdctvfs",
    "bqlporuefkwzyamnsmgjdctvfs",
    "bqlporuexkwzyahqimgjdazvfs",
    "bqspocuexkwzyahnimgjdctffs",
    "bqlporuexkwzywhnimgjiccvfs",
    "bqlcoruexkwzyahnimgjdgtvfj",
    "bqljoruexkwvyahnimgcdctvfs",
    "bqeporuexkwzyahnionjdctvfs",
    "bqlporuexkwzyabnxmgjqctvfs",
    "bqjporuexkwzyahnimtddctvfs",
    "bqlprruexkezyahbimgjdctvfs",
    "bqlporuexkazyahnimgjjctefs",
    "bqlioruexkweyjhnimgjdctvfs",
    "bqlporuexsszymhnimgjdctvfs",
    "bqlporffxkwzyahnimgjditvfs",
    "bqlporuexkwzyahnimcedctvbs",
    "bqwpgruexkezyahnimgjdctvfs",
    "bqldoruexkwzyahnimgjdcpvfu",
    "bqlpoxueckwzyahnemgjdctvfs",
    "bqlhoruqxkwzyahnimgjdctsfs",
    "wqlporuexkwzychfimgjdctvfs",
    "bqlporuenkwzyahnimvqdctvfs",
    "aqlppruexkwzyahnimgjdcrvfs",
    "bqlporuexzwzfahnimgjdcivfs",
    "bqjporuexkwzyahnimgjdcqmfs",
    "bqppkkuexkwzyahnimgjdctvfs",
    "bqlporuervwzyahnimgldctvfs",
    "bqoporxeykwzyahnimgjdctvfs",
    "bqyporuehkwzyahnilgjdctvfs",
    "bqlporuexkwzybvnimgjdctvfv",
    "bqlporzehkwzyaznimgjdctvfs",
    "bqiporuexkjzyahnimgjdatvfs",
    "yqlpkruexkwzyahnimggdctvfs",
    "brlporuexkwzyehnimgjdctvbs",
    "bqlporuyxkwzyahnapgjdctvfs",
    "bqlporuexkwzyaewimgjdttvfs",
    "bqlporueskwzyahnimpjdcdvfs",
    "bqlioruexkwzyahnimghdcbvfs",
    "bqljoruexkwzyahtimgjdctmfs",
    "bqlporgexkwzyaxnimgjvctvfs",
    "bqlporuexkwxyahnimgodftvfs",
    "mqlporupxkwzyahnimgjdcqvfs",
    "bgkporuexkwzychnimgjdctvfs",
    "jqlporuexgwzyawnimgjdctvfs",
    "bqlperuebkwzyahniwgjdctvfs",
    "bqlporuexkwzyahnbmgjdntvts",
    "bqlporuexkwzyajnimgldctvfz",
    "bqlpobuexkwzychnimgjdctvfu",
    "bquporuexkwzyahiimgjdctvfp",
    "bnlporbexkwzyahnimgjdctvfb",
    "bqlporuexklzyahnimgtdctbfs",
    "bqlworuexkwzyahnimkjdcpvfs",
    "bqlporumxkwzyahnikejdctvfs",
    "bqlporuexkwryahnimfjdctnfs",
    "bqlioruenkwzywhnimgjdctvfs",
    "bqlporulxbwzyahnimgjdctvfe",
    "bqeporufxkwzqahnimgjdctvfs",
    "bqlpbwuexkwzyahnimgjdctvfo",
    "bqlpoduexkwzyahnimgvdctvrs",
    "bqlporuexkwzlahnimgjdctvdw",
    "bqlporuexkwzyahnimujdctdfp",
    "iqlporuexvwvyahnimgjdctvfs",
    "bclporuexkwzyahnimgjdzovfs",
    "bqlporuerktzyahnamgjdctvfs",
    "bqlporuexkwziajnimgjdctvfe",
    "bqlpnrkexkwoyahnimgjdctvfs",
    "bqlporuexkwznacnimgjdctvks",
    "bqlporuexkrzyrhnimgjdcuvfs",
    "bqltoruexkwzyahnnmgjdcivfs",
    "bqlporuexkwzuahnimdjdctmfs",
    "bqlporubxkbzyahnimgjdctmfs",
    "bqlplruexkwdyhhnimgjdctvfs",
    "bylporuexknzyahnimgjdctmfs",
    "bqlporuexkwzyahqitgjdctvas",
    "bquperuexkwzyahnimgjdcdvfs",
    "bqlporuexktzyahnisgjdctvls",
    "bqlporuexkwfyacnimtjdctvfs",
    "bqleoraexkwzyahnimgjoctvfs",
    "bqlporuexkwlyahnimrjdctvas",
    "bqlphruexkwzyadnimujdctvfs",
    "oqadoruexkwzyahnimgjdctvfs",
    "belpzruexkwzyahnimgjjctvfs",
    "bqlporuexkwzkahtbmgjdctvfs",
    "bqlporulctwzyahnimgjdctvfs",
    "bklptrwexkwzyahnimgjdctvfs",
    "bqlpoqhexkwzjahnimgjdctvfs",
    "tqlporjexkwzyahnimgjdctvfx",
    "bqipwruexkwzyahnimgjdctvfd",
    "bqlparueeawzyahnimgjdctvfs",
    "bqlsoruexkrzyahnqmgjdctvfs",
    "bqlsoruexhwzwahnimgjdctvfs",
    "bquporuexkwsyihnimgjdctvfs",
    "bwlporuexkwzyahwimgjdcuvfs",
    "bqgpobuexkczyahnimgjdctvfs",
    "bqlporuexkwzyahntmgjdspvfs",
    "bqlporuetkwzjavnimgjdctvfs",
    "bqlpoluwxkwzyahnimgpdctvfs",
    "bqlporueykwzuahnimgjuctvfs",
    "bqqporuexkwzyranimgjdctvfs",
    "bjlporuexkwzyahnjmgjdctvts",
    "bjlpofuenkwzyahnimgjdctvfs",
    "bqhporuexbwzyahnfmgjdctvfs",
    "bqlpofulxkwzyfhnimgjdctvfs",
    "bqlporuexrwzyahuimgjdcwvfs",
    "bblporaexkwzyahnicgjdctvfs",
    "uqlpoxuexkwzuahnimgjdctvfs",
    "bqlporuexkwzylhnimgjjhtvfs",
    "bqlloruexkhiyahnimgjdctvfs",
    "bqlpopuexkwzyahnymojdctvfs",
    "bqlporuexkwgyyhnimgjdstvfs",
    "bqlroruexxwzyahnumgjdctvfs",
    "balpopuexkwzeahnimgjdctvfs",
    "bqlporuexkwzyahniogjdqtvfc",
    "bqlpoiuexkwgynhnimgjdctvfs",
    "bqlpoyueukwzyahnimgjdcwvfs",
    "bqtporuexkwtyahnimgjdctvfl",
    "bqlporzexkwzyahnsmgjdctxfs",
    "bqlporukxkwhyahnimgddctvfs",
    "bklporuevowzyahnimgjdctvfs",
    "bqgporuexmwzyahnimgjdctsfs",
    "bqlporuetkxzyahnimgjoctvfs",
    "bqlpsrzexkwzyahnimcjdctvfs",
    "bqlporuexkwzzahaimgkdctvfs",
    "bqlporuexkwzyahnimgjdmtvwd",
    "bqlporuexkwzywhlimgjhctvfs",
    "bqlporuexkwuhahnimgjdctvns",
    "bqqporuexkizyahnimgjdctcfs",
    "bqlvoruepkbzyahnimgjdctvfs",
    "bqlporuexkwqyahnimgjfctvbs",
    "bqlporuexkwzyahlimghuctvfs",
    "bqlporuexkwzyahnizgjictvfb",
    "bqlporuvxkjzyahaimgjdctvfs",
    "bqljoruexkwzyahnizgjdctqfs",
    "bqlporuexkwyyahnimgjdztvfv",
    "jqlporqexkwzyahvimgjdctvfs",
    "bqlporueakwzyabnimgjdctxfs",
    "bqlporuezewzyahnimgfdctvfs",
    "bqlporuzxklzyahnwmgjdctvfs",
    "zqlpproexkwzyahnimgjdctvfs",
    "bqlporuefkwzyahnlmgjdgtvfs",
    "bqlporoenkwzyahnkmgjdctvfs",
    "bqwporuexkwzyahnimcjdctvfk",
    "bqlporuexkwbyahaimgjdctvus",
    "bqlporujxkwzyahnimgjfntvfs",
    "bqlooruexkvzyahnimjjdctvfs",
    "bqlpomuexowzyahnimgjcctvfs",
    "bqlpoquexkwzvahnimgjdctvfl",
    "bclpopuexowzyahnimgjdctvfs",
    "bqlporuexcwzyahnimgjdctlfb",
    "bqlporgexkwzyalnimgjdctvfq",
    "bqppiruexkwzyyhnimgjdctvfs",
    "bqlporaexkwnmahnimgjdctvfs",
    "bqhporuexkwzyahlomgjdctvfs",
    "bqlloruexkwzuahnimgjdctvfb",
    "bqhporuexkwzyahnemgjdcovfs",
    "bqlpiruexkwdyahwimgjdctvfs",
    "bqlporuexkwryahnimgjtdtvfs",
    "bqeporuexkwzyahgixgjdctvfs",
    "bqlporuexkwyqahnimgfdctvfs",
    "bqlporuexkwzyaoniggydctvfs",
    "bqlpouuexkazyahnimgxdctvfs",
    "brlporuexkwzyahvimgjdctvps",
    "bqlforuexkwzyrhnitgjdctvfs",
    "bqlpiruexkwzyfhnjmgjdctvfs",
    "bqlpoebexkwzyxhnimgjdctvfs",
    "bblporoezkwzyahnimgjdctvfs",
    "bglporuexkwzyajqimgjdctvfs",
    "bqlpxcuixkwzyahnimgjdctvfs",
    "bqlporuaekwzyahniegjdctvfs",
    "hqvporuexkwzyahnimgjectvfs",
    "qllporuexkwzyahnimgjdctvhs",
    "bqlporaexkpzyahnlmgjdctvfs",
    "bqlporuexkwzyabnzmgjqctvfs",
    "bqlporuexbvzyahnimgjdctrfs",
    "bqdzoruetkwzyahnimgjdctvfs",
    "bslporuexkwzyahnimgjdctdos",
    "bqlporfexkwzylwnimgjdctvfs",
    "bqrporueykwzyavnimgjdctvfs",
    "bqlporuexkweythnomgjdctvfs",
    "bqlpozuepkwzyahnimgjdctdfs",
    "bqoporuexqhzyahnimgjdctvfs",
    "bqlporucxkwzyahnimtjdctifs",
    "bqlpobuexawzyahnimgjdcthfs",
    "dklporuexkwzyahnimhjdctvfs",
    "bclpkquexkwzyahnimgjdctvfs",
    "bqlporuexkwzyafnfmljdctvfs",
    "bqlporuexkwzympnimgjsctvfs",
    "bqlporuexkwzyaonimdjactvfs",
    "bqlporuvxkwzywhnimgjdctvks",
    "bqlporuexkwzgahnimbjdctvfn",
    "bqlqoruexvwzqahnimgjdctvfs",
    "bqlporuexkmkyahniggjdctvfs",
    "bqlneruexkwzyjhnimgjdctvfs",
    "bqlporueqkwzyahnbmgjdctvfl",
    "bqlpgruexkwzyahnimjvdctvfs",
    "nqlpsruevkwzyahnimgjdctvfs",
    "bqhpouuexkwzyahnmmgjdctvfs",
    "bqnporuexkwzyahnimojdctqfs",
    "bqlpordexkwztahnimgjdctvds",
    "eqlporufxkwzyahniigjdctvfs",
    "balporuebkwzyahnimgjdctvfv",
    "bqlprruexrwzwahnimgjdctvfs",
    "bqlporuepkwxyahnimggdctvfs",
    "bqlporfexkwzyahnqjgjdctvfs",
    "bqaporuexvwzyahnimgjdctvfy",
    "bqlporuexkwzyawnibgjdctmfs",
    "eqlhoruexkwzyahiimgjdctvfs",
    "bqlporuexkbzyahnimgsdhtvfs",
    "bqlporhexkfzyahnimgjdcgvfs",
    "bqeporuexkxzyahnimgjdcavfs",
    "bqlporoerkwzyahnimgjdctnfs",
    "bqlporuemkwzyshnimgjdatvfs",
    "bilporuexkwyyahnimgvdctvfs",
    "xqlporuexkwzyahnnmgjdctvfl",
    "bqlborumxkwzsahnimgjdctvfs",
    "bqlporsexcwzvahnimgjdctvfs",
    "bqlporxexkwzyapnimgbdctvfs",
    "bqlpmruexkwzyahnimgbdcpvfs",
    "qqlroruexkwzyahnihgjdctvfs",
    "bqnporuexkbzyaknimgjdctvfs",
    "bqxpoeuexcwzyahnimgjdctvfs",
    "bqlporuexkqzyahnidgjdcivfs",
    "zqkmoruexkwzyahnimgjdctvfs",
    "bqlporuexkwzyahzimgjqjtvfs",
    "bqfporuenkwzyahiimgjdctvfs",
    "bqlporuexkwzyahuimszdctvfs",
    "bklporurmkwzyahnimgjdctvfs",
    "bqlpotuexktzyahnimgjdcfvfs",
    "bqlporuexkwxyahnimgxdltvfs",
    "bqmporuexkwzoahnimgjdctvys",
    "bqlporuexvwzyahnimgjdnnvfs",
    "bqzporuexkwzyahnkmgjdctsfs",
    "bqmporuexkwzyahnihgjdctvfq",
    "bqlporuexkwzyavnimgjdcrvos",
    "bklpopuexkwzyahnimgjdctvfb",
    "bvlcoruexkwzyapnimgjdctvfs",
    "bqlboruexzwcyahnimgjdctvfs",
    "bqlporuexdwzyihnimgydctvfs",
    "bqlpovuexkwzyaynimgjdctvfq",
    "bqlarruebkwzyahnimgjdctvfs",
    "fqlporuexkwzfahnimgjdctsfs",
    "bqlporuexowzyahnjmgjdctdfs",
    "bqlporuexkwzyahnrmkjdctyfs"
)